services:
  db:
    image: postgres:17
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    env_file:
      - .env
    container_name: api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    command:
      ["sh", "-c", "prisma generate && prisma migrate deploy && python main.py"]

volumes:
  db-data: {}
